---
kind: Metric
id: telegraf_prometheus_azure_vmss_metrics
collector: telegraf
metadata:
  inputs:
    prometheus:
      - urls: [http://0.0.0.0:9090/metrics]
        period: 1m
        delay: 0s
        interval: 1m
        namepass: [nginx_connections_waiting] # This metric represents the wating number of connections that the nginx reserves. If this value remains high, it signifies that the nginx is using a significant amount of connections, which could trigger a scale-out.
  outputs:
    wave-autoscale: {}
---

