apiVersion: v1
kind: ConfigMap
metadata:
  name: wave-config
  labels:
    app.kubernetes.io/name: wave-autoscale-config
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: wave-autoscale
data:
  wave-config.yaml: |
    # Data Layer
    db_url: {{ .Values.config.db_url }}
    watch_definition_duration: {{ .Values.config.watch_definition_duration }}
    autoscaling_history_retention: {{ .Values.config.autoscaling_history_retention }}
    reset_definitions_on_startup: {{ .Values.config.reset_definitions_on_startup }}

    # API Server
    host: {{ .Values.config.host }}
    port: {{ .Values.config.port }}
    
    # Web Console
    web_ui: {{ .Values.config.web_ui }}
    web_ui_host: {{ .Values.config.web_ui_host }}
    web_ui_port: {{ .Values.config.web_ui_port }}

    vector:
      macos_x86_64: {{ .Values.config.vector.macos_x86_64 }}
      macos_aarch64: {{ .Values.config.vector.macos_aarch64 }}
      linux_x86_64: {{ .Values.config.vector.linux_x86_64 }}
      linux_aarch64: {{ .Values.config.vector.linux_aarch64 }}
      windows_x86_64: {{ .Values.config.vector.windows_x86_64 }}
    telegraf:
      macos_x86_64: {{ .Values.config.telegraf.macos_x86_64 }}
      macos_aarch64: {{ .Values.config.telegraf.macos_aarch64 }}
      linux_x86_64: {{ .Values.config.telegraf.linux_x86_64 }}
      linux_aarch64: {{ .Values.config.telegraf.linux_aarch64 }}
      windows_x86_64: {{ .Values.config.telegraf.windows_x86_64 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wave-definitions
  labels:
    app.kubernetes.io/name: wave-autoscale-definitions
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: definitions
    app.kubernetes.io/part-of: wave-autoscale
data:
  definitions.yaml: |
    # Your definitions.yaml content here.
    # See https://waveautoscale.com/docs/guide/getting-started/ for more information.
    # https://vector.dev/docs/reference/configuration/sources/host_metrics/
    ---
    kind: Metric
    id: vector_host_metrics
    collector: vector
    metadata:
      sources:
        my_source_id_1:
          type: host_metrics
          namespace: host
          scrape_interval_secs: 5
      sinks:
        my_sinks_id:
          type: wave-autoscale
          inputs: ["my_source_id_1"]
