[workspace]
members = [
    "core/wave-autoscale",
    "core/api-server",
    "core/data-layer",
    "core/utils",
]

[workspace.package]
rust-version = "1.70.0"
authors = ["Wave Autoscale Team in STCLab, Inc"]
documentation = "https://waveautoscale.com/docs"