[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.test-data-reader]
command = "cargo"
args = ["test", "reader", "--", "--nocapture"]

[tasks.test-controller-metric]
command = "cargo"
args = ["test", "metric_adapter_test", "--", "--nocapture"]

[tasks.test-controller-metric-cloudwatch]
command = "cargo"
args = ["test", "metric_adapter_test::cloudwatch", "--", "--nocapture"]

[tasks.test-controller-scaling-component]
command = "cargo"
args = ["test", "scaling_component_test", "--", "--nocapture"]

[tasks.test-controller-planner]
command = "cargo"
args = ["test", "scaling_planner_test", "--", "--nocapture"]
