services:
  wave-autoscale:
    image: "waveautoscale/wave-autoscale:test"
    ports:
      - "3024:3024"
      - "3025:3025"
    volumes:
      - ".:/usr/src/wave-autoscale"
    command: "./wave-autoscale --config /usr/src/wave-autoscale/wave-config.yaml"
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
