services:
  wave-autoscale:
    depends_on:
      postgres:
        condition: service_healthy
    image: "waveautoscale/wave-autoscale:latest"
    ports:
      - "3024:3024"
      - "3025:3025"
    volumes:
      - ".:/usr/src/wave-autoscale"
    command: "./wave-autoscale --config /usr/src/wave-autoscale/wave-config.yaml"
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
