[package]
name = "utils"
license = "Apache-2.0"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.70"
serde = { version = "1.0.157", features = ["derive"] }
serde_yaml = "0.9.19"
tracing = { version = "0.1.40" }

[dev-dependencies]
tracing-test = { version = "0.2.4" }
