kind: Metric
id: wa_metric_example
collector: wa-generator
enabled: true
metadata:
  pattern: [50, 60, 70, 80, 90, 100]
  gap_seconds: 5
---
kind: ScalingComponent
id: wa_scaling_component_example
component_kind: wa-logger
enabled: true
metadata:
---
kind: ScalingPlan
id: wa_scaling_plan_example
enabled: true
metadata:
  title: "Scaling Plan for K8S Deployment Scaling - deployment replicas"
  cool_down: 60 # seconds
  interval: 5000 # milliseconds
plans:
  - id: plan-1
    description: "Plan Example 1"
    expression: >
      get({
        metric_id: 'wa_metric_example',
        period_sec: 5
      }) >= 70
    priority: 1
    scaling_components:
      - component_id: "wa_scaling_component_example"
