name: Integration tests
run-name: ${{ github.actor }} has created a pull request
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
      - 'release-*'

env:
  CARGO_TERM_COLOR: always

jobs:
  test-on-pull-request:
    runs-on: wave-autoscale-runner
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        timeout-minutes: 1

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        timeout-minutes: 5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/advisory-db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Set up moon cache
        uses: actions/cache@v3
        continue-on-error: false
        timeout-minutes: 10
        with:
          path: |
            .moon/cache/
          key: ${{ runner.os }}-moon-${{ hashFiles('**/moon.yml','.moon/**/*') }}
          restore-keys: |
            ${{ runner.os }}-moon-

      - name: Install Moonrepo
        uses: moonrepo/setup-moon-action@v1

      - name: Install Clippy
        run: rustup component add clippy
      
      # WORKAROUND: moon 1.13.2 has a bug of cargo binstall
      - name: Install BInstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
      
      - name: Install cargo-nextest
        run: cargo binstall -y cargo-nextest
      
      - name: Install cargo-cache
        run: cargo binstall -y cargo-cache
      
      - name: Install cargo-deny
        run: cargo binstall -y cargo-deny
      ## END OF WORKAROUND

      - name: Cargo-deny Check (Licenses, Bans)
        run: cargo deny check licenses ban

      # - name: Run audit
      #   run: moon run archiver:audit -f

      # - name: Run lint
      #   run: moon run :lint -f

      - name: Run test
        run: moon run controller:test -f

      - name: Cargo Autoclean
        run: moon run archiver:clean-cargo-cache -f
