name: Publish Docker Image
on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-push:
    runs-on: wave-autoscale-build-runner
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        timeout-minutes: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: waveautoscale/wave-autoscale:latest
          cache-from: type=registry,ref=waveautoscale/wave-autoscale:buildcache
          cache-to: type=registry,ref=waveautoscale/wave-autoscale:buildcache,mode=max
          labels: |
            org.opencontainers.image.title=wave-autoscale
            org.opencontainers.image.description="Wave Autoscale is a open-source traffic & scaling automation tool."
            org.opencontainers.image.url="https://waveautoscale.com"
